version: "3.7"

services:
  proxy:
    image: httpd
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HTTPD_CONF}:/usr/local/apache2/conf/httpd.conf
      - ${HTTPD_SSL_CONF}:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ${SSL_CERT}:/usr/local/apache2/conf/server.crt
      - ${SSL_KEY}:/usr/local/apache2/conf/server.key
    networks:
      - container
    dns:
      - ${DNS1}
      - ${DNS2}
  node:
    image: "node:19"
    user: ${NODE_USER}
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - ./package.json:/home/node/app/package.json
    ports:
      - 3030:3030/tcp
    command: "npm start"
    networks:
      - container

  prisma-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    networks:
      - container

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=omar7410!
    ports:
      - 1433:1433
    volumes:
      - ./:/app
    networks:
      - container

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
