version: "3.7"

services:
  proxy:
    image: httpd
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HTTPD_CONF}:/usr/local/apache2/conf/httpd.conf
      - ${HTTPD_SSL_CONF}:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ${SSL_CERT}:/usr/local/apache2/conf/server.crt
      - ${SSL_KEY}:/usr/local/apache2/conf/server.key
    networks:
      - container
    dns:
      - ${DNS1}
      - ${DNS2}

  prisma-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - container

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=omar7410!

    ports:
      - 1433:1433
    volumes:
      - ./:/app
    networks:
      - container

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
