version: "3.7"

services:
  proxy:
    image: httpd
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/conf//httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./certs/server.crt:/usr/local/apache2/conf/server.crt
      - ./certs/server.key:/usr/local/apache2/conf/server.key
    networks:
      - container
    dns:
      - 8.8.8.8
      - 1.1.1.1
  node:
    image: "node:19"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - 3000:3000/tcp
    command: /bin/bash -c "npm install && npm start && apt-get update && apt-get install openssl "
    networks:
      - container

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=omar7410!
    ports:
      - 1433:1433
    volumes:
      - ./:/app
    networks:
      - container

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
